server:
  port: 7002

spring:
  application:
    name: cloud-eureka-server2

eureka:
  instance:
    hostname: eureka7002.com #eureka server的instance名
  client:
    register-with-eureka: false #false表示不在注册中心注册自己
    fetch-registry: false #false表示本机是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务的服务地址
      defaultZone: http://eureka7001.com:7001/eureka/ #互相注册 其实是http:/127.0.0.1:7001/eureka/